kind: ConfigMap
apiVersion: v1
metadata:
 name: kubedns-config
 namespace: default
data:
 devopsbp.dns: devopsbp-k8s-microservice
 devopsbp.port: "8081"
---
kind: Service
apiVersion: v1
metadata:
  name: devopsbp-k8s-microservice
spec:
  selector:
    app: devopsbp-k8s-microservice
  ports:
  - protocol: TCP
    port: 8081
    name: theport
  type: LoadBalancer 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsbp-k8s-microservice
spec:
  selector:
      matchLabels:
        app: devopsbp-k8s-microservice
  replicas: 3
  template:
    metadata:
      labels:
        app: devopsbp-k8s-microservice
    spec:
      containers:
        - name: devopsbp-k8s-microservice
          image: registry.gitlab.com/mmarquezvacas/java-microservice
          ports:
            - containerPort: 8081
---
apiVersion: apps/v1
kind: Service
metadata:
  name: devopsbp-k8s-microservice-service
  labels:
    app: devopsbp-k8s-microservice
spec:
  type: NodePort
  ports:
    - port: 8081
      nodePort: 30001
      protocol: TCP
  selector:
app: devopsbp-k8s-microservice

