kind: ConfigMap
apiVersion: v1
metadata:
 name: kubedns-config
 namespace: default
data:
 devopsbp.dns: devopsbp-k8s-microservice
 devopsbp.port: "8081"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsbp-k8s-microservice
spec:
  selector:
      matchLabels:
        app: devopsbp-k8s-microservice
  replicas: 3
  template:
    metadata:
      labels:
        app: devopsbp-k8s-microservice
    spec:
      containers:
        - name: devopsbp-k8s-microservice
          image: registry.gitlab.com/mmarquezvacas/java-microservice
          ports:
            - containerPort: 8081
---
kind: Service
apiVersion: v1
metadata:
  name: devopsbp-k8s-microservice
  labels:
    app: devopsbp-k8s-microservice
spec:
  type: NodePort
  ports:
    - port: 8081
      nodePort: 30001
      protocol: TCP
  selector:
    app: devopsbp-k8s-microservice
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tls-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "devopsbp-ip-name"
spec:
  tls:
  - secretName: devopscert
  backend:
    serviceName: devopsbp-k8s-microservice
    servicePort: 8081
---

