version: 2.1
jobs:
  build:
    docker:
        - image: circleci/8u212-b04-jdk-stretch
    steps:
      - checkout
      - run:
        name: Maven Build
        command: mvn package -Dmaven.test.skip=true -B spring-boot:repackage
workflows:
  bp-circleci-workflow:
    jobs:
      - build