version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u212-b04-jdk-stretch
    working_directory: ~/java-microservice
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - sample-springboot-api-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: sample-springboot-api-{{ checksum "pom.xml" }}
      - run: mvn package -Dmaven.test.skip=true -B spring-boot:repackage